# Generated by Django 3.1.7 on 2021-03-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
