# Generated by Django 3.1.7 on 2021-05-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=6)),
                ('order_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contact_no', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Deleted'), (1, 'Pending'), (2, 'Close')])),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_code', models.CharField(max_length=10)),
                ('type', models.IntegerField(choices=[(0, 'Local'), (1, 'Air'), (2, 'Sea')])),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_placement_date', models.DateField()),
                ('preparation_date', models.DateField()),
                ('loading_date', models.DateField()),
                ('received_date', models.DateField()),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('freight_Charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sl_transport_charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ch_transport_charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('initial_payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('balance_payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alibaba_initial_charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alibaba_balance_charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alibaba_total_charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stamp_duty', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_shipping_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping_cost_factor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.IntegerField(choices=[(0, 'Deleted'), (1, 'Pending'), (2, 'Shipped'), (3, 'Received'), (4, 'Apprved'), (5, 'Close')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.agent')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('warranty_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.IntegerField(choices=[(0, 'Deleted'), (1, 'Pending'), (2, 'Apprved'), (3, 'Close')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.product')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.IntegerField(choices=[(0, 'Deleted'), (1, 'Pending'), (2, 'Apprved'), (3, 'Close')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.shipment')),
            ],
            options={
                'unique_together': {('shipment', 'product')},
            },
        ),
    ]
