# Generated by Django 3.1.7 on 2021-05-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_auto_20210508_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
