# Generated by Django 3.1.7 on 2021-05-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_remove_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
