# Generated by Django 3.1.7 on 2021-05-08 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210508_2251'),
        ('sim', '0004_auto_20210508_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.customer'),
        ),
    ]
