# Generated by Django 3.1.7 on 2021-05-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0005_auto_20210508_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='freight_Charge',
            new_name='freight_charge',
        ),
        migrations.AddField(
            model_name='shipment',
            name='agent_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
